### ISSUE TITLE
Process exited before completing request

### ISSUE THREAD

**Issue by mikedizon** [TaylorBriggs/mailchimp-lambda#1]
New to Lambda. Are there any particular settings or permissios to apply when uploading the zip?

**Comment by mikedizon** [comment]
Printed out the errors. Seems that the URL needs to be configurable.

**Comment by TaylorBriggs** [comment]
To configure your mailchimp URL, you can use a `.env` file to assign your values. Should look something like this:

```
API_KEY=YOUR_API_KEY
LIST_ID=YOUR_LIST_ID
USERNAME=YOUR_USERNAME
```

Configuring the Lamdba to respond to requests made to a URL is a little more complex. You'll need to set everything up in AWS. Here are a few resources from their documentation on how to set that up: http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html
http://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https-example.html
